steps:
  # 1. Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'terraform init'

  # 2. Destroy and save output to tf_output.txt (continue so parser can upload errors)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'set -o pipefail; terraform destroy -auto-approve -no-color | tee tf_output.txt'
    id: destroy
    continueOnError: true

  # 3. Parse the output and upload to GCS (Destroy or Failed)
  - name: 'python:3.9-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install google-cloud-storage
        python audit_parser.py tf_output.txt gcp-playground-2305-tf-audits "Destroy"
    waitFor: ['destroy']

options:
  logging: CLOUD_LOGGING_ONLY