steps:
  # 1. Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'terraform init'

  # 2. Destroy + Parse (parser runs in same step so it always uploads success or failure to GCS)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set +e
        terraform destroy -auto-approve -no-color 2>&1 | tee tf_output.txt
        D=$?
        apk add --no-cache python3 py3-pip >/dev/null 2>&1 && pip3 install google-cloud-storage && python3 audit_parser.py tf_output.txt gcp-playground-2305-tf-audits "Destroy"
        [ $D -ne 0 ] && exit $D
        exit 0

options:
  logging: CLOUD_LOGGING_ONLY